### ISSUE TITLE
Slowness prevents using for larger XML files

### ISSUE THREAD

**Issue by villelaitila** [fatihpense/rust_xml_oxide#5]
I've done little benchmarking with SAX parsers (Rust based), and the performance with large models, e.g. with millions of XML nodes, seems to be a blocker issue with this library. Are there any ways to optimize it in order to use CPU efficiently, maybe doing parallel processing, or optimizing the usage of data structures, or should I instead focus on the other libraries available? I really like the interface of rust_xml_sax.

**Comment by fatihpense** [comment]
Hello Ville,
Thanks for the comment! It is a hobby project at the moment. I actually wanted to validate the idea of the interface and get feedback from the community. My idea was to gather feedback about the interface from people that knows more about Rust library/API design, iron out the interface details with a draft implementation, and then work out implementation details or maybe a new implementation from scratch. You are the first person I could get feedback from, so thanks for your feedback! Now we are 2 people that like the interface :) And that is enough for me to look at the problem again.

Unfortunately, it may take time. Since I'm not developing on Rust in my day job, I'm a bit rusty...

I advise using another library for the performance at the moment. But I'm open to design discussions anytime.

Regards,
Fatih

**Comment by fatihpense** [comment]
Hello Ville,
I experimented with a different design and it is a lot faster now. Parsing 1GB XML with 20350677 nodes takes around 25 seconds. Though it can become slower as I add features, I believe it will stay in the reasonable time range.

I changed the rust_xml_sax interface to be a pull parser, so basically just an enum. I think this is much easier for the users of the library in terms of lifetime/ownership. Can you tell me if you think it is worse now?

I will add some important features, change the readme, examples, and do a cleanup. But the new parser can be tested as below.

```toml
[dependencies]
xml_oxide = "0.0.8"
xml_sax = "0.0.5"
```

```rust
use std::fs::File;

use xml_oxide::parser3::OxideParser;

fn main() {
    println!("Hello, world!");

    let mut counter: usize = 0;
    let mut end_counter: usize = 0;


    use std::time::Instant;
    let now = Instant::now();

// change the file path
    let f = File::open(
        "C:/wikidump.xml",
    )
    .unwrap();

    let mut p = OxideParser::start(f);

    loop {
        let res = p.read_event();
        // println!("{:?}", res);
        match res {
            xml_sax::Event::StartDocument => todo!(),
            xml_sax::Event::EndDocument => todo!(),
            xml_sax::Event::StartElement(el) => {
                counter = counter + 1;
                // print every 10000th element name
                if counter % 10000 == 0 {
                    println!("%10000 start {}", el.name);
                }
            }
            xml_sax::Event::EndElement(el) => {
                end_counter += 1;
                if el.name == "feed" {
                    break;
                }
            }
            xml_sax::Event::Characters(_) => {}
            xml_sax::Event::Reference(_) => {}
        }
    }

    println!("START EVENT COUNT:{}", counter);
    println!("END EVENT COUNT:{}", end_counter);

    let elapsed = now.elapsed();
    println!("Elapsed: {:.2?}", elapsed);
}

```

**Comment by fatihpense** [comment]
Hello Ville,
I reduced the number down to 19 seconds. I think from this point on, it won't go up with the additional features.

You can use crate version 0.3.0 or up, with the examples in doc.rs or Readme.
```toml
[dependencies]
xml_oxide = "0.3.0"
```

I'm closing this issue but we can continue to discuss the design anytime here.
Regards
